import ProjectPlaybook from './project-playbook';
type Briefing = { title: string; intro: string; output: string; items: { title: string; text: string; steps: string[]; result: string }[] };

export const briefings: Record<string, Briefing> = {
  inicio: {
    title: 'O projeto, por dentro.', intro: 'Um roteiro de apresentação para conhecer a proposta e discutir sua implantação com a administração.', output: 'Uma proposta adaptável, com compromissos verificáveis.',
    items: [
      { title: 'O que estamos apresentando', text: 'Uma proposta de organização de uma unidade virtual: pessoas, formação, rotina, documentação e acompanhamento. A implantação depende de alinhamento com a administração que receberá o projeto.', steps: ['Conhecer os programas em Projetos.', 'Consultar o comando e as responsabilidades em Hierarquia.', 'Comparar a formação proposta com as necessidades locais.'], result: 'Uma visão comum sobre escopo e responsabilidades.' },
      { title: 'Como avaliar a proposta', text: 'A apresentação deve permitir perguntas e ajustes. Não é necessário aprovar todos os programas de uma vez: o plano pode começar com um núcleo inicial e crescer após avaliação.', steps: ['Definir prioridades e limites de atuação.', 'Identificar recursos disponíveis e pendências.', 'Registrar decisões, responsáveis e próxima revisão.'], result: 'Uma decisão fundamentada, sem promessas de resultados garantidos.' },
      { title: 'O que precisa ser combinado', text: 'Regras locais, horários, critérios de ingresso e canais de comunicação devem ser acordados antes da ativação. O site apresenta o modelo; não substitui esse acordo.', steps: ['Validar a identidade e a estrutura da unidade.', 'Aprovar o calendário e os critérios de avaliação.', 'Definir o contato responsável pela administração.'], result: 'Uma implantação compatível com a comunidade que receberá o 18º.' },
    ],
  },
  projeto: {
    title: 'Programas que saem do papel.', intro: 'Quatro frentes propostas, cada uma com uma entrega concreta e uma forma de acompanhar sua evolução.', output: 'Portfólio de programas com revisão periódica pelo comando.',
    items: [
      { title: 'Programa Integra 18 — recepção e adaptação', text: 'Organizar a chegada de novos integrantes, apresentando a cultura da unidade, as regras locais e a rotina esperada. O RH coordena o ingresso; um orientador pode ser designado para cada turma.', steps: ['Apresentação da unidade e confirmação de disponibilidade.', 'Leitura orientada das normas e espaço para dúvidas.', 'Acompanhamento inicial com devolutiva individual.'], result: 'Ficha de integração e registro das orientações recebidas.' },
      { title: 'Academia contínua — formação e reciclagem', text: 'Manter um calendário previsível de instruções, com turmas compatíveis com a disponibilidade do efetivo. A proposta combina base comum, especializações e recuperação orientada.', steps: ['Levantar necessidades a partir dos relatórios.', 'Publicar temas, pré-requisitos e instrutores designados.', 'Revisar o conteúdo quando houver mudança nas regras.'], result: 'Calendário de formação, registro de participação e plano de desenvolvimento.' },
      { title: 'Unidade integrada — intercâmbio de equipes', text: 'Propor atividades conjuntas com outras unidades, mediante autorização da administração. O foco é comunicação, divisão de responsabilidades e respeito aos limites de cada equipe.', steps: ['Acordar objetivo, participantes e regras da atividade.', 'Realizar exercício virtual supervisionado.', 'Produzir avaliação conjunta sem exposição desnecessária de integrantes.'], result: 'Relatório de integração com melhorias acordadas entre as equipes.' },
      { title: 'Memória e qualidade — aprender com a rotina', text: 'Criar uma biblioteca interna de materiais aprovados e lições aprendidas. Relatos públicos devem preservar a privacidade e evitar transformar situações individuais em exposição.', steps: ['Padronizar modelos de briefing e relatório.', 'Separar material em revisão de material aprovado.', 'Revisar documentos com responsável e data definidos.'], result: 'Acervo organizado e plano de melhorias acompanhado pelo comando.' },
    ],
  },
  operacao: {
    title: 'Uma rotina com começo, meio e revisão.', intro: 'Organização de atividades no ambiente virtual. O painel acima é uma representação demonstrativa, não um sistema de monitoramento real.', output: 'Cada ciclo deixa um registro útil para o próximo.',
    items: [
      { title: 'Abertura do turno', text: 'Antes de iniciar, a supervisão confirma quem está disponível, a atividade prevista e os canais autorizados. A prioridade é trabalhar dentro das regras e da capacidade real da equipe.', steps: ['Confirmar presença, funções e responsável pelo turno.', 'Apresentar objetivo, limites e dúvidas do briefing.', 'Registrar alterações de escala e impedimentos.'], result: 'Briefing resumido, compreendido pelos participantes.' },
      { title: 'Comunicação e coordenação', text: 'Manter mensagens objetivas, respeito entre equipes e encaminhamento de decisões ao responsável adequado. Alterações relevantes devem ser comunicadas sem criar ordens conflitantes.', steps: ['Identificar a equipe e o assunto antes de solicitar apoio.', 'Confirmar orientações relevantes para evitar interpretações diferentes.', 'Encaminhar conflitos de regra para supervisão e administração.'], result: 'Uma cadeia de comunicação clara, com menos ruído.' },
      { title: 'Encerramento e aprendizado', text: 'O encerramento deve registrar o que ocorreu, o que dificultou o trabalho e o que merece revisão. O relatório é instrumento de aprendizado, não competição por quantidade.', steps: ['Resumir atividades e situações que exigiram orientação.', 'Separar fatos observados de opiniões.', 'Atribuir responsável e prazo às melhorias aprovadas.'], result: 'Relatório breve com ações de melhoria acompanháveis.' },
    ],
  },
  estrutura: {
    title: 'Patente, função e responsabilidade.', intro: 'A hierarquia organiza decisões. A designação de uma função específica deve ser registrada e comunicada ao efetivo.', output: 'Responsabilidades visíveis, com substituição e encaminhamento definidos.',
    items: [
      { title: 'Comando e continuidade', text: 'Rafael Aguiar permanece como responsável geral, com Jeraldo no posto de major. Decisões sobre implantação e mudanças de estrutura devem ser consolidadas pelo comando.', steps: ['Registrar decisões e responsáveis por executá-las.', 'Definir substituição para períodos de ausência.', 'Comunicar mudanças de função antes de sua aplicação.'], result: 'Continuidade da gestão sem ordens sobrepostas.' },
      { title: 'RH, tecnologia e criação do projeto', text: 'O CAP PM Gabriel Santos é o criador deste projeto e o responsável por todos os desenvolvimentos e iniciativas tecnológicas do 18º BPM/M — Virtual. À frente da concepção e da evolução das soluções digitais da unidade, transforma ideias em ferramentas que fortalecem a organização, a identidade e a modernização do batalhão. Sua atuação também abrange a gestão de Recursos Humanos e o acompanhamento do efetivo.', steps: ['Conceber e conduzir os projetos, sistemas e soluções tecnológicas do 18º BPM/M.', 'Coordenar a evolução deste projeto, integrando apresentação institucional, conteúdo e experiência digital.', 'Manter a organização do RH, consolidar necessidades de capacitação e encaminhar propostas de progressão ao comando.'], result: 'Tecnologia e gestão de pessoas a serviço de uma unidade mais organizada, integrada e preparada para evoluir.' },
      { title: 'Motos e designações especializadas', text: 'O 2º TEN PM H. Smith é o responsável informado pela unidade de motos. Participação em funções especializadas depende de formação, avaliação e autorização interna.', steps: ['Verificar pré-requisitos e disponibilidade.', 'Designar supervisão para atividades formativas.', 'Registrar habilitação interna e necessidade de reciclagem.'], result: 'Especialização vinculada ao preparo, não apenas à patente.' },
      { title: 'Progressão e reconhecimento', text: 'Como proposta, a progressão deve considerar conduta, participação, preparo e capacidade de assumir responsabilidades. Tempo de casa ou conclusão isolada de um curso não geram promoção automática.', steps: ['Publicar critérios antes do ciclo de avaliação.', 'Oferecer devolutiva e possibilidade de revisão.', 'Registrar a decisão e as metas de desenvolvimento.'], result: 'Um processo de reconhecimento compreensível e revisável.' },
    ],
  },
  formacao: {
    title: 'Aprender. Demonstrar. Evoluir.', intro: 'Matriz e cargas horárias propostas para formação interna virtual, sujeitas à aprovação do comando. Não equivalem a certificações profissionais reais.', output: 'Registro de aprendizagem, com devolutiva e oportunidade de recuperação.',
    items: [
      { title: 'Trilha básica — comunicação e procedimentos', text: 'Modulação e B.O. PM, P.O.P./Carceragem e Abordagem e Posicionamento compõem a base sugerida. Influenciam a clareza dos relatos, o conhecimento das regras e a postura em simulações.', steps: ['Pré-requisito: integração e leitura das regras locais.', 'Atividade: produzir relato de um cenário fictício e explicar decisões.', 'Avaliação: clareza, respeito às regras e capacidade de corrigir falhas.'], result: 'Base comum antes da participação em módulos avançados.' },
      { title: 'Trilha progressiva — TAT e SAT', text: 'TAT I, II e III devem ter progressão acompanhada. SAT-A e SAT-B aprofundam competências definidas pela equipe de instrução. Ementas e significados das siglas devem ser formalizados antes de abrir turmas.', steps: ['Pré-requisito: conclusão da base e liberação do instrutor.', 'Atividade: simulações virtuais com papéis e regras previamente definidos.', 'Avaliação: cooperação, julgamento e cumprimento dos limites do exercício.'], result: 'Evolução gradual com ementa e critérios conhecidos pelos alunos.' },
      { title: 'Mobilidade e liderança — funções específicas', text: 'Direção Defensiva apoia a condução responsável no ambiente virtual. Pelotão RPM/ROCAM, Comandante RPM/ROCAM e CFC devem preparar o integrante para as responsabilidades da função pretendida.', steps: ['Pré-requisito: base concluída e perfil compatível com a função.', 'Atividade: planejamento de exercício, comunicação e avaliação da equipe.', 'Avaliação: organização, responsabilidade e capacidade de orientar colegas.'], result: 'Designações apoiadas em preparo demonstrado e validação interna.' },
      { title: 'Avaliação, recuperação e reciclagem', text: 'A presença é registrada separadamente da aprovação. Cada turma deve divulgar critérios e instrumentos de avaliação antes do início, sem alterar exigências ao final do curso.', steps: ['Registrar desempenho por competência, não apenas uma nota geral.', 'Oferecer feedback individual e atividade de recuperação.', 'Reavaliar após mudança de regras ou dificuldade recorrente.'], result: 'Ficha com curso, instrutor, data, resultado e próxima orientação.' },
      { title: 'Oficinas complementares propostas', text: 'Ampliar a formação com temas que melhoram a convivência e a qualidade da gestão: redação de relatórios, mediação de conflitos, ética digital e formação de instrutores.', steps: ['Relatórios: separar fatos, contexto e encaminhamentos.', 'Convivência: escuta, respeito e encaminhamento de conflitos.', 'Instrutores: planejar aula, explicar critérios e dar devolutivas úteis.'], result: 'Novas oficinas a aprovar; não são turmas já abertas nem certificações existentes.' },
    ],
  },
  gestao: {
    title: 'Gestão que pode ser acompanhada.', intro: 'Processos propostos para organizar pessoas, proteger registros e transformar problemas em decisões claras.', output: 'Uma rotina administrativa simples, documentada e revisável.',
    items: [
      { title: 'Ingresso, escala e acompanhamento', text: 'O RH organiza inscrições, disponibilidade e integração. A escala deve ser construída de acordo com a presença possível, sem prometer cobertura que o efetivo não consegue oferecer.', steps: ['Informar critérios de ingresso e etapas da seleção.', 'Coletar apenas informações necessárias à participação.', 'Prever canal para ausências e ajustes de disponibilidade.'], result: 'Cadastro atualizado e escala compatível com o efetivo.' },
      { title: 'Indicadores com significado', text: 'Acompanhar participação, formação e pendências usando critérios consistentes. Os números devem servir para identificar necessidades, não gerar rankings automáticos de valor pessoal.', steps: ['Participação: presenças sobre atividades previstas para o integrante.', 'Formação: competências avaliadas e recuperações pendentes.', 'Melhorias: ações concluídas sobre ações previstas para o período.'], result: 'Resumo periódico com contexto; nenhum dado real é coletado por este site.' },
      { title: 'Conduta, escuta e revisão', text: 'Relatos de problemas devem ser recebidos por um responsável designado, com registro objetivo, escuta dos envolvidos e encaminhamento conforme as regras locais.', steps: ['Separar recebimento do relato de decisão sobre o caso.', 'Restringir a exposição a quem precisa acompanhar.', 'Informar encaminhamento e possibilidade de revisão.'], result: 'Tratamento respeitoso, sem julgamentos públicos antecipados.' },
      { title: 'Documentação e proteção de registros', text: 'Manter modelos únicos, responsáveis identificados e acesso proporcional à função. Materiais de apresentação pública não devem conter registros pessoais de avaliação ou ocorrências internas.', steps: ['Identificar versão, responsável e data de revisão.', 'Definir quem pode consultar e alterar cada registro.', 'Revisar acessos quando alguém mudar de função ou sair.'], result: 'Documentos confiáveis e menor exposição de informações pessoais.' },
    ],
  },
  implantacao: {
    title: 'Noventa dias, entregas claras.', intro: 'Cronograma de referência, ajustável à aprovação e à disponibilidade local. Cada etapa avança mediante validação, não apenas pelo calendário.', output: 'Ativação acompanhada, com pendências e critérios de continuidade explícitos.',
    items: [
      { title: 'Dias 1–15 · alinhamento e desenho', text: 'Consolidar escopo, regras, responsáveis e recursos disponíveis com a administração. Identificar o que precisa ser adaptado antes de iniciar a formação.', steps: ['Entrega: documento de escopo e matriz de responsabilidades.', 'Dependência: concordância da administração e do comando.', 'Critério de avanço: limites, contatos e pendências registrados.'], result: 'Plano inicial aprovado, sem assumir autorização implícita.' },
      { title: 'Dias 16–30 · integração e formação básica', text: 'Organizar a primeira turma, confirmar disponibilidade e aplicar a base comum. Registrar dificuldades para ajustar o ritmo do calendário.', steps: ['Entrega: turma integrada e avaliações iniciais registradas.', 'Dependência: instrutores designados e materiais aprovados.', 'Critério de avanço: lacunas identificadas e recuperação planejada.'], result: 'Um núcleo inicial com preparo acompanhado.' },
      { title: 'Dias 31–60 · piloto supervisionado', text: 'Testar a rotina em atividades virtuais autorizadas, com escopo limitado e supervisão. Usar os relatórios para corrigir comunicação, documentação e organização.', steps: ['Entrega: registros do piloto e plano de correções.', 'Dependência: autorização local e responsáveis presentes.', 'Critério de avanço: revisão do comando sobre pendências críticas.'], result: 'Modelo ajustado antes de ampliar a participação.' },
      { title: 'Dias 61–90 · consolidação e revisão', text: 'Revisar resultados com a administração, definir a rotina seguinte e aprovar expansão apenas quando houver capacidade. A revisão pode manter, reduzir ou ampliar o escopo.', steps: ['Entrega: relatório de ciclo e calendário seguinte.', 'Dependência: avaliação das entregas anteriores.', 'Critério de continuidade: acordo sobre capacidade, metas e revisões.'], result: 'Próximo ciclo acordado e documentado.' },
    ],
  },
};

export default function CategoryBriefing({ category }: { category: string }) {
  const data = briefings[category];
  return <section className="category-briefing">
    <header className="briefing-heading"><div><p className="kicker">CADERNO DO PROJETO / DETALHAMENTO</p><h2>{data.title}</h2></div><p>{data.intro}</p></header>
    <div className="briefing-body"><aside><span>PLANO PROPOSTO</span><b>{String(data.items.length).padStart(2, '0')}</b><p>frentes para explorar</p><small>Abra cada tópico para consultar a aplicação, as etapas e a entrega esperada.</small><div><i /> LEITURA POR TÓPICOS</div></aside>
      <div className="briefing-accordions">{data.items.map((item, i) => <details key={item.title} open={i === 0}><summary><span>{String(i + 1).padStart(2, '0')}</span><h3>{item.title}</h3><b aria-hidden="true">+</b></summary><div className="briefing-detail"><p>{item.text}</p><ol>{item.steps.map(step => <li key={step}>{step}</li>)}</ol><footer><span>ENTREGA ESPERADA</span><p>{item.result}</p></footer></div></details>)}</div>
    </div><div className="briefing-outcome"><span>COMPROMISSO DO MÓDULO</span><p>{data.output}</p></div>
    <ProjectPlaybook category={category} />
  </section>;
}
