'use client';

import { useState } from 'react';
import { flushSync } from 'react-dom';

const stages = [
  { title: 'Alinhar antes de assumir', label: 'Preparação', text: 'A primeira conversa é com a administração. A proposta do 18º precisa caber nas regras, nos recursos e nas necessidades de quem recebe a unidade.', items: ['Definir atribuições e limites de atuação.', 'Confirmar recursos e disponibilidade do efetivo.', 'Registrar os pontos acordados com a administração.'], output: 'Plano de implantação alinhado entre as partes.' },
  { title: 'Entrar em serviço com direção', label: 'Briefing', text: 'Antes de iniciar, a equipe precisa saber quem coordena, qual é sua função e como pedir apoio. O briefing reúne essas decisões em uma orientação objetiva.', items: ['Conferir presença e qualificação dos integrantes.', 'Distribuir funções e responsáveis pela supervisão.', 'Repassar prioridades e canais de comunicação.'], output: 'Equipe orientada e funções registradas.' },
  { title: 'Trabalhar como uma unidade', label: 'Atuação', text: 'A proposta é manter supervisão presente e comunicação entre equipes. A unidade de motos integra o planejamento, sem funcionar como uma estrutura isolada.', items: ['Manter o comando informado das atividades.', 'Respeitar as regras e os limites acordados.', 'Registrar fatos relevantes para a revisão posterior.'], output: 'Atividades documentadas e acompanhamento pelo comando.' },
  { title: 'Fechar o ciclo, corrigir o próximo', label: 'Revisão', text: 'Depois da atividade, o debriefing separa o que funcionou, o que precisa mudar e o que deve virar instrução. O registro serve para aprender, não para produzir números decorativos.', items: ['Ouvir os integrantes envolvidos.', 'Identificar dificuldades de comunicação e organização.', 'Definir uma melhoria com responsável e prazo.'], output: 'Relatório curto e ações de melhoria acompanháveis.' },
];

const courses = [
  { name: 'Modulação e B.O. PM', group: 'Fundamentos', hours: '4h', goal: 'Falar com clareza e registrar o que aconteceu.', impact: 'Melhora a passagem de informações e permite que outra equipe compreenda um registro sem depender de explicações adicionais.', entry: 'Integração inicial da unidade.', practice: 'Exercícios de rádio e elaboração de um boletim a partir de um cenário fictício.', assessment: 'Clareza, sequência dos fatos e preenchimento dos campos previstos.' },
  { name: 'P.O.P. / Carceragem', group: 'Fundamentos', hours: '4h', goal: 'Conhecer responsabilidades e seguir uma sequência de registros.', impact: 'Evita improvisos administrativos e reforça o respeito às regras de custódia da comunidade.', entry: 'Modulação e B.O. PM.', practice: 'Simulação de conferência documental e passagem de responsabilidade, conforme as regras locais.', assessment: 'Completude dos registros e identificação do responsável por cada etapa.' },
  { name: 'Abordagem e Posicionamento', group: 'Fundamentos', hours: '6h', goal: 'Priorizar verbalização, postura e coordenação em cenários virtuais.', impact: 'Ajuda o integrante a agir com respeito, controlar a comunicação e reconhecer os limites de sua função.', entry: 'Integração e regras locais concluídas.', practice: 'Cenários simulados de atendimento e tomada de decisão com acompanhamento do instrutor.', assessment: 'Respeito às regras, comunicação e justificativa das decisões.' },
  { name: 'Direção Defensiva', group: 'Mobilidade', hours: '6h', goal: 'Conduzir com responsabilidade e reconhecer situações de risco.', impact: 'Reduz conduções imprudentes e melhora a organização dos deslocamentos da equipe.', entry: 'Integração e autorização interna de condução.', practice: 'Percursos simulados com avaliação de atenção, prevenção e cuidado com outros participantes.', assessment: 'Condução segura e respeito às regras de trânsito da comunidade.' },
  { name: 'TAT I', group: 'Progressão', hours: '8h', goal: 'Construir uma base comum de trabalho em equipe.', impact: 'Estabelece linguagem, responsabilidades e hábitos de comunicação compartilhados.', entry: 'Módulos fundamentais concluídos.', practice: 'Exercícios virtuais de cooperação com funções previamente distribuídas.', assessment: 'Disciplina, comunicação e cumprimento da função atribuída.' },
  { name: 'TAT II', group: 'Progressão', hours: '8h', goal: 'Integrar equipes em situações simuladas com mais variáveis.', impact: 'Aprimora a leitura conjunta de uma situação e a capacidade de ajustar decisões sem perder a organização.', entry: 'TAT I aprovado.', practice: 'Simulações de coordenação e resolução de problemas com feedback ao final.', assessment: 'Integração, comunicação e coerência das decisões.' },
  { name: 'TAT III', group: 'Progressão', hours: '10h', goal: 'Desenvolver supervisão e liderança de equipe.', impact: 'Prepara lideranças para orientar, acompanhar e corrigir o trabalho sem concentrar todas as tarefas.', entry: 'TAT II aprovado e indicação para desenvolvimento de liderança.', practice: 'Planejamento de uma atividade simulada, briefing e condução de debriefing.', assessment: 'Clareza da orientação, acompanhamento e qualidade do feedback.' },
  { name: 'SAT-A', group: 'Especialização', hours: '6h', goal: 'Reforçar competências que precisam de prática acompanhada.', impact: 'Transforma dificuldades observadas em objetivos individuais de desenvolvimento.', entry: 'Base concluída; conteúdo específico a validar pela instrução.', practice: 'Estações formativas adaptadas às necessidades identificadas nas avaliações.', assessment: 'Evolução em relação aos objetivos definidos para o participante.' },
  { name: 'SAT-B', group: 'Especialização', hours: '8h', goal: 'Consolidar o aprendizado em uma avaliação integrada.', impact: 'Verifica se o integrante mantém consistência ao combinar diferentes competências.', entry: 'SAT-A aprovado; ementa a validar pela instrução.', practice: 'Cenário virtual integrado com critérios apresentados antes da avaliação.', assessment: 'Consistência, comunicação e respeito aos procedimentos acordados.' },
  { name: 'CFC', group: 'Liderança', hours: '12h', goal: 'Desenvolver liderança, instrução e acompanhamento de pessoas.', impact: 'Ajuda futuros responsáveis a organizar escalas, orientar integrantes e acompanhar a evolução da equipe.', entry: 'Indicação do comando e histórico formativo analisado.', practice: 'Preparar uma instrução curta, organizar uma escala e realizar feedback orientado.', assessment: 'Organização, qualidade da instrução e postura na gestão de pessoas.' },
  { name: 'Pelotão RPM / ROCAM', group: 'Mobilidade', hours: '8h', goal: 'Integrar a unidade de motocicletas ao restante do batalhão.', impact: 'Organiza comunicação, responsabilidades e participação do pelotão nas atividades previstas.', entry: 'Direção Defensiva e seleção interna da unidade de motos.', practice: 'Atividades virtuais de condução responsável, comunicação e coordenação do grupo.', assessment: 'Segurança na condução e integração com os demais participantes.' },
  { name: 'Comandante RPM / ROCAM', group: 'Liderança', hours: '10h', goal: 'Preparar quem vai organizar e acompanhar o pelotão.', impact: 'Torna explícitas as responsabilidades da liderança pela formação e pelo acompanhamento de seus integrantes.', entry: 'Formação do pelotão e indicação do comando.', practice: 'Elaborar plano de instrução, distribuir responsabilidades e conduzir uma revisão de atividade.', assessment: 'Planejamento, supervisão e clareza do relatório final.' },
];
const command = [
  ['TEN-CEL', 'Rafael Aguiar', 'Responsável geral', 'Direção do projeto, alinhamento com a administração e validação das decisões da unidade.'],
  ['MAJ PM', 'Jeraldo', 'Subcomando', 'Coordenação interna e acompanhamento das atividades em apoio ao comando geral.'],
  ['CAP PM', 'Gabriel Santos', 'Recursos humanos', 'Organização do efetivo, disponibilidade, registros e acompanhamento dos integrantes.'],
  ['1º TEN PM', 'Valdir', 'Oficial', 'Integra a cadeia de comando. Atribuições específicas definidas pelo comando geral.'],
  ['2º TEN PM', 'H. Smith', 'Unidade de motos', 'Organização do pelotão, formação específica e integração com o restante da unidade.'],
];
const roster = [['ASP PM','Vitor'],['1º SGT PM','Derek Oliveira'],['1º SGT PM','Vitor Hugo'],['3º SGT PM','Jota Bueno'],['ALN SGT PM','Arthur Portella'],['CB PM','Marcos Silva'],['CB PM','Felipe Almeida'],['CB PM','Maycon Rios'],['SD PM','Joao Cavalcante'],['SD PM','Matheus Silva'],['SD PM','Birel Costa']];
const groups = ['Todos', 'Fundamentos', 'Progressão', 'Mobilidade', 'Especialização', 'Liderança'];

function Crest({ className = '' }: { className?: string }) {
  return <img className={`crest ${className}`} src="./baep-crest-360-web.png" alt="Brasão BAEP — Ações Especiais" width="631" height="595" />;
}
function SectionHeading({ number, label, title, children }: { number: string; label: string; title: string; children?: React.ReactNode }) {
  return <header className="section-heading"><div><span className="eyebrow">{number} / {label}</span><h2>{title}</h2></div>{children && <p>{children}</p>}</header>;
}

export default function Home() {
  const [menu, setMenu] = useState(false);
  const [stage, setStage] = useState(0);
  const [group, setGroup] = useState('Todos');
  const [query, setQuery] = useState('');
  const [spin, setSpin] = useState(false);
  function printProject() {
    const previousGroup = group;
    const previousQuery = query;
    const openNames = new Set(Array.from(document.querySelectorAll<HTMLDetailsElement>('details[open]')).map(item => item.querySelector('summary')?.textContent));
    flushSync(() => { setGroup('Todos'); setQuery(''); });
    document.querySelectorAll<HTMLDetailsElement>('details').forEach(item => { item.open = true; });
    window.addEventListener('afterprint', () => {
      document.querySelectorAll<HTMLDetailsElement>('details').forEach(item => { item.open = openNames.has(item.querySelector('summary')?.textContent); });
      setGroup(previousGroup);
      setQuery(previousQuery);
    }, { once: true });
    window.print();
  }
  const selected = stages[stage];
  const filtered = courses.filter(c => (group === 'Todos' || c.group === group) && `${c.name} ${c.goal}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));
  return <>
    <a className="skip-link" href="#conteudo">Ir para o conteúdo</a>
    <header className="site-header"><a href="#inicio" className="brand"><span className="brand-mark">18<span>º</span></span><span><b>BPM/M <i>— VIRTUAL</i></b><small>PROJETO DE IMPLANTAÇÃO BAEP</small></span></a><button className="menu-toggle" aria-expanded={menu} aria-controls="navigation" onClick={() => setMenu(!menu)}>{menu ? 'Fechar −' : 'Menu +'}</button><nav id="navigation" className={menu ? 'is-open' : ''} aria-label="Navegação principal">{[['O projeto','projeto'],['Atuação','operacao'],['Comando','estrutura'],['Cursos','formacao']].map(([label,id]) => <a key={id} href={`#${id}`} onClick={() => setMenu(false)}>{label}</a>)}<a className="nav-contact" href="#implantacao" onClick={() => setMenu(false)}>Plano de implantação <span>↗</span></a></nav></header>
    <main id="conteudo">
      <section className="hero wrap" id="inicio"><div className="hero-topline"><span><i className="status-dot" /> DOCUMENTO DE APRESENTAÇÃO</span><span>18º BPM/M · PROJETO GERAL</span></div><div className="hero-layout"><div className="hero-copy"><span className="eyebrow">Batalhão de Ações Especiais</span><h1>O nome é BAEP.<br /><em>O compromisso<br />é nosso.</em></h1><p>O 18º BPM/M – Virtual apresenta sua proposta para assumir uma unidade BAEP: comando definido, formação acompanhada e uma rotina de trabalho que possa ser cobrada.</p><div className="hero-actions"><a className="button" href="#projeto">Conheça a proposta <span>↗</span></a><a className="text-link" href="#formacao">Ver os cursos <span>↓</span></a></div><div className="hero-note"><span>SEM DESTINO FIXO</span><p>Um projeto adaptável à comunidade que receber a unidade.</p></div></div><div className="emblem-panel"><div className="panel-caption"><span>IDENTIDADE / AÇÕES ESPECIAIS</span><span>18 / BAEP</span></div><div className="emblem-stage"><div className="emblem-orbit" aria-hidden="true" /><div className="emblem-line" aria-hidden="true" /><Crest className={spin ? 'is-spinning' : ''} /></div><div className="panel-bottom"><div><span>APRESENTADO PELO</span><strong>18º BPM/M — Virtual</strong></div><button className="rotation-control" onClick={() => setSpin(!spin)} aria-pressed={spin}>{spin ? 'Pausar giro Ⅱ' : 'Girar brasão ↻'}</button></div><p className="panel-footnote">Identidade visual de referência · projeto virtual independente</p></div></div><div className="hero-footer"><span>Disciplina no trato. Clareza no comando. Constância no preparo.</span><a href="#projeto">Leia o projeto <b>↓</b></a></div></section>

      <section className="proposal section wrap" id="projeto"><SectionHeading number="01" label="A proposta" title="Antes de assumir, organizar.">A apresentação não substitui o alinhamento com a administração. Ela mostra o que propomos, quem responde e como pretendemos colocar em prática.</SectionHeading><div className="proposal-layout"><div className="statement"><span className="label">NOSSA PROPOSTA</span><h3>Não basta reunir um efetivo.<br />É preciso dar direção a ele.</h3><p>O projeto do 18º reúne uma estrutura de comando, uma matriz de cursos e um plano de implantação. A intenção é começar com responsabilidades claras e ampliar a atuação conforme a equipe demonstrar preparo.</p><p>As regras da comunidade e os acordos com sua administração orientam toda a implantação. Funções, cronograma e recursos são ajustados antes da ativação.</p><a className="text-link" href="#estrutura">Quem responde pelo projeto <span>↗</span></a></div><div className="commitments">{[['Comando que acompanha','Cada área tem um responsável. Dúvidas, mudanças e decisões devem percorrer uma cadeia de comando compreensível.'],['Formação que faz diferença','O curso precisa ter objetivo, avaliação e retorno ao integrante. Presença sozinha não comprova aprendizado.'],['Rotina que deixa registro','Briefings, relatórios e revisões ajudam a manter continuidade, mesmo quando as equipes mudam.']].map(([title,text],i) => <article key={title}><span className="item-number">0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>

      <section className="operations section" id="operacao"><div className="wrap"><SectionHeading number="02" label="Rotina da unidade" title="Do alinhamento à revisão.">Selecione uma etapa para conhecer a rotina proposta. Este painel explica o fluxo de trabalho; não representa monitoramento ao vivo.</SectionHeading><div className="operations-panel"><div className="stage-tabs" aria-label="Etapas de atuação">{stages.map((item,i)=><button key={item.label} aria-pressed={stage===i} aria-controls="stage-detail" onClick={()=>setStage(i)}><span>0{i+1}</span>{item.label}<b>{stage===i?'−':'+'}</b></button>)}</div><div className="stage-content" id="stage-detail"><div className="flow-visual" aria-hidden="true"><div className="flow-radar"><div className="radar-sweep"/><span className="radar-center">18º<br/><small>COMANDO</small></span>{stages.map((item,i)=><span key={item.label} className={`flow-point point-${i} ${stage===i?'selected':''}`}><i/>{item.label}</span>)}</div><span className="diagram-label">FLUXO ILUSTRATIVO / 04 ETAPAS</span></div><div className="stage-text" key={stage} aria-live="polite"><span className="eyebrow">ETAPA 0{stage+1}</span><h3>{selected.title}</h3><p>{selected.text}</p><ul>{selected.items.map(item=><li key={item}>{item}</li>)}</ul><div className="stage-output"><span>O QUE FICA REGISTRADO</span><p>{selected.output}</p></div></div></div></div></div></section>

      <section className="section wrap command-section" id="estrutura"><SectionHeading number="03" label="Pessoas e responsabilidades" title="Uma cadeia de comando. Nomes definidos.">Esta é a composição apresentada pelo 18º. As atribuições específicas são alinhadas antes da implantação.</SectionHeading><div className="command-grid">{command.map(([rank,name,role,desc],i)=><article className={i===0?'command-card chief':'command-card'} key={name}><div className="command-top"><span>{rank}</span><small>0{i+1}</small></div><h3>{name}</h3><span className="role">{role}</span><p>{desc}</p></article>)}</div><details className="roster"><summary><span>Quadro complementar do efetivo <small>{roster.length} integrantes relacionados</small></span><b>+</b></summary><div className="roster-list">{roster.map(([rank,name])=><div key={name}><span>{rank}</span><strong>{name}</strong></div>)}</div></details><div className="structure-note"><span>RESPONSABILIDADES A DESIGNAR</span><p>Instrutores, apoio administrativo e responsáveis pela avaliação serão definidos pelo comando conforme disponibilidade e qualificação. Não são apresentados aqui como setores já em funcionamento.</p></div></section>

      <section className="academy section" id="formacao"><div className="wrap"><SectionHeading number="04" label="Matriz de formação" title="Curso não é só uma sigla.">Veja o objetivo, o que cada curso muda na unidade e como o aprendizado pode ser avaliado. Abra uma ficha para conhecer a proposta.</SectionHeading><div className="formation-notice"><span>PROPOSTA FORMATIVA</span><p>Cargas horárias e ementas são sugestões para validação pelo comando e pela administração. Conteúdos destinados exclusivamente ao ambiente virtual, sem certificação profissional real.</p></div><div className="course-toolbar"><div className="course-filters" aria-label="Filtrar cursos">{groups.map(item=><button key={item} aria-pressed={group===item} onClick={()=>setGroup(item)}>{item}</button>)}</div><label className="course-search"><span className="sr-only">Buscar curso</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar curso..." type="search"/><span aria-hidden="true">⌕</span></label></div><div className="course-result" aria-live="polite">{filtered.length} {filtered.length===1?'curso encontrado':'cursos encontrados'}<span>Horas sugeridas · conteúdo expansível</span></div><div className="course-list">{filtered.map(course=><details className="course" key={course.name}><summary><span className="course-index">{String(courses.indexOf(course)+1).padStart(2,'0')}</span><div className="course-title"><span>{course.group}</span><h3>{course.name}</h3><p>{course.goal}</p></div><span className="course-hours">{course.hours}<small>proposta</small></span><b className="expand-icon">+</b></summary><div className="course-body"><div className="course-impact"><span className="label">O QUE MUDA NA UNIDADE</span><p>{course.impact}</p></div><dl><div><dt>Pré-requisito proposto</dt><dd>{course.entry}</dd></div><div><dt>Como será trabalhado</dt><dd>{course.practice}</dd></div><div><dt>O que será avaliado</dt><dd>{course.assessment}</dd></div></dl></div></details>)}</div>{filtered.length===0&&<div className="empty-state"><p>Nenhum curso corresponde à busca.</p><button onClick={()=>{setQuery('');setGroup('Todos');}}>Limpar filtros</button></div>}<div className="learning-path"><h3>Uma trilha, não uma coleção de cursos.</h3><ol><li><b>01</b><span>Conhecer as regras<small>Integração e fundamentos</small></span></li><li><b>02</b><span>Praticar acompanhado<small>Instrução e simulação</small></span></li><li><b>03</b><span>Receber avaliação<small>Critérios e feedback</small></span></li><li><b>04</b><span>Revisar o aprendizado<small>Reciclagem e evolução</small></span></li></ol></div></div></section>

      <section className="section wrap implementation" id="implantacao"><SectionHeading number="05" label="Da proposta à prática" title="Assumir por etapas. Ampliar com critério.">Um cronograma inicial de referência, ajustável à disponibilidade da equipe. Os períodos abaixo são uma proposta, não uma promessa de ativação.</SectionHeading><div className="timeline">{[['01—15','Alinhamento e organização','Revisar regras, confirmar responsáveis e levantar disponibilidade.','Plano acordado e quadro de funções.'],['16—30','Formação de base','Aplicar integração e módulos fundamentais, com avaliações registradas.','Mapa de formação e pendências por integrante.'],['31—60','Atuação acompanhada','Realizar atividades-piloto permitidas e revisar comunicação e organização.','Relatórios de acompanhamento e ajustes.'],['61—90','Revisão e consolidação','Avaliar a experiência inicial antes de ampliar o escopo de atuação.','Parecer do comando e plano do próximo ciclo.']].map(([days,title,desc,delivery])=><article key={days}><span className="timeline-days">DIAS <b>{days}</b></span><h3>{title}</h3><p>{desc}</p><div><span>ENTREGA PREVISTA</span><p>{delivery}</p></div></article>)}</div><div className="activation"><div><span className="eyebrow">ANTES DA ATIVAÇÃO</span><h3>O que precisa estar combinado.</h3></div><ul>{['Regras, atribuições e limites aprovados pela administração.','Responsáveis e disponibilidade do efetivo confirmados.','Formação mínima concluída e pendências conhecidas.','Recursos autorizados e rotina de registros organizada.'].map(item=><li key={item}>{item}</li>)}</ul></div></section>

      <section className="accountability section"><div className="wrap accountability-grid"><div><span className="eyebrow">06 / Acompanhamento</span><h2>Menos números de vitrine.<br/><em>Mais retorno sobre o trabalho.</em></h2><p>Os indicadores serão preenchidos com registros reais da unidade após a implantação. Até lá, mostramos o que pretendemos observar.</p></div><div className="metrics">{[['Efetivo','Disponibilidade informada e participação nas atividades.','A cada escala'],['Formação','Conclusões, dificuldades e reciclagens necessárias.','Após cada curso'],['Rotina','Qualidade dos registros e cumprimento dos acordos.','A cada ciclo'],['Desenvolvimento','Feedbacks e ações de melhoria efetivamente concluídas.','Na revisão do comando']].map(([name,desc,freq])=><article key={name}><div><h3>{name}</h3><p>{desc}</p></div><span>{freq}</span></article>)}</div></div></section>

      <section className="closing wrap"><div className="closing-stamp">18º<span>BPM/M — VIRTUAL</span></div><div><span className="eyebrow">PROJETO DE IMPLANTAÇÃO BAEP</span><h2>Prontos para apresentar.<br/><em>Dispostos a construir junto.</em></h2><p>O próximo passo é alinhar esta proposta com a administração da comunidade: regras, equipe, recursos e prioridades.</p><div className="closing-actions"><a className="button" href="#estrutura">Conhecer o comando <span>↗</span></a><button className="text-link" onClick={printProject}>Imprimir o projeto <span>↗</span></button></div></div></section>
    </main><footer className="site-footer wrap"><div><b>18º BPM/M — Virtual</b><p>Projeto independente, sem vínculo com órgãos públicos reais.<br/>Brasão utilizado como referência visual no contexto virtual.</p></div><a href="#inicio">Voltar ao início ↑</a></footer>
  </>;
}
