import { redirect } from 'next/navigation';
import { isAdminRequest } from '../../lib/admin-auth';
import PrintButton from './print-button';

export const dynamic = 'force-dynamic';

const courses = [
  ['Modulação e B.O. PM','4h','Comunicação e registros padronizados'],['P.O.P. / Carceragem','4h','Procedimentos, responsabilidade e documentação'],['Abordagem e Posicionamento','6h','Postura, comunicação e segurança'],['Direção Defensiva','6h','Prevenção e condução responsável'],['TAT I','8h','Base operacional e disciplina de equipe'],['TAT II','8h','Integração e cenários simulados'],['TAT III','10h','Liderança e coordenação avançada'],['SAT-A','6h','Aperfeiçoamento técnico supervisionado'],['SAT-B','8h','Consolidação e certificação'],['CFC','12h','Formação de liderança e gestão'],['Pelotão RPM / ROCAM','8h','Mobilidade e trabalho em equipe'],['Comandante RPM / ROCAM','10h','Planejamento, supervisão e avaliação']
];

export default async function DocumentPage() {
  if (!await isAdminRequest()) redirect('/admin');
  return <main className="project-document"><nav className="document-tools"><a href="/admin">← VOLTAR AO PAINEL</a><span>Use “Salvar como PDF” na janela de impressão.</span><PrintButton/></nav>
    <section className="doc-cover"><div className="doc-mark">18</div><small>18º BPM/M — VIRTUAL</small><h1>PROJETO DE<br/><em>IMPLANTAÇÃO BAEP</em></h1><p>Estrutura, formação, gestão e modelo de atuação para apresentação institucional virtual.</p><footer><b>DOCUMENTO DE APRESENTAÇÃO</b><span>VERSÃO {new Date().getFullYear()}</span></footer></section>
    <section className="doc-page"><header><span>01</span><div><small>VISÃO EXECUTIVA</small><h2>PROPÓSITO DO PROJETO</h2></div></header><p className="doc-lead">Construir uma unidade virtual organizada, preparada e capaz de assumir sua implantação com cadeia de comando definida, formação progressiva e acompanhamento contínuo.</p><div className="doc-columns">{[['MISSÃO','Desenvolver uma estrutura de excelência apoiada em disciplina, preparo, liderança e responsabilidade.'],['MODELO','Diagnóstico, planejamento, distribuição de equipes, execução coordenada e avaliação.'],['ENTREGA','Uma proposta geral, adaptável à cidade que receber a unidade, sem vínculo territorial fixo.']].map(([t,d])=><article key={t}><h3>{t}</h3><p>{d}</p></article>)}</div><h3 className="doc-subtitle">PRINCÍPIOS</h3><ul className="doc-list"><li>Comando e responsabilidades claramente definidos.</li><li>Formação teórica, prática, avaliação e reciclagem.</li><li>Registro de decisões, indicadores e melhoria contínua.</li><li>Integração responsável com as demais unidades virtuais.</li></ul></section>
    <section className="doc-page"><header><span>02</span><div><small>CADEIA DE COMANDO</small><h2>ESTRUTURA DA UNIDADE</h2></div></header><div className="doc-hierarchy">{[['TEN-CEL Rafael Aguiar','Responsável geral'],['MAJ PM Jeraldo','Subcomando'],['CAP PM Gabriel Santos','RH, desenvolvimento, tecnologia e criador do projeto'],['1º TEN PM Valdir','Oficial'],['2º TEN PM H. Smith','Responsável pela unidade de motos']].map(([n,f],i)=><article key={n}><b>{String(i+1).padStart(2,'0')}</b><div><h3>{n}</h3><p>{f}</p></div></article>)}</div><aside className="doc-note"><b>GESTÃO E TECNOLOGIA</b><p>O CAP PM Gabriel Santos responde pelos desenvolvimentos e pelas iniciativas tecnológicas realizadas no 18º BPM/M — Virtual, atuando também na gestão de Recursos Humanos e na autoria deste projeto.</p></aside></section>
    <section className="doc-page"><header><span>03</span><div><small>MATRIZ FORMATIVA</small><h2>CURSOS PROPOSTOS</h2></div></header><div className="doc-course-table"><div><b>CURSO</b><b>CARGA</b><b>RESULTADO ESPERADO</b></div>{courses.map(course=><div key={course[0]}><strong>{course[0]}</strong><span>{course[1]}</span><p>{course[2]}</p></div>)}</div><p className="doc-footnote">A matriz é uma proposta interna para ambiente virtual. Conteúdos, critérios e cargas podem ser adaptados e validados pelo comando.</p></section>
    <section className="doc-page"><header><span>04</span><div><small>ROTEIRO DE ENTREGA</small><h2>IMPLANTAÇÃO EM QUATRO FASES</h2></div></header><div className="doc-phases">{[['01','ESTRUTURAÇÃO','Comando, funções, normas, identidade e documentação.'],['02','CAPACITAÇÃO','Cursos, instruções e exercícios integrados.'],['03','VALIDAÇÃO','Avaliações, simulações e registro da prontidão.'],['04','ATIVAÇÃO','Início acompanhado, indicadores e melhoria contínua.']].map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}</div><h3 className="doc-subtitle">ENTREGAS ESSENCIAIS</h3><ul className="doc-list"><li>Plano inicial de 90 dias.</li><li>Matriz de responsabilidades e substituições.</li><li>Relatório de prontidão do efetivo.</li><li>Ciclo periódico de revisão e melhoria.</li></ul><footer className="doc-sign"><div><span>COMANDO GERAL</span></div><div><span>RESPONSÁVEL PELO PROJETO</span></div></footer></section>
    <footer className="doc-disclaimer">PROJETO VIRTUAL INDEPENDENTE · SEM VÍNCULO COM ÓRGÃOS PÚBLICOS REAIS</footer>
  </main>;
}
