import { redirect } from 'next/navigation';
import { isAdminRequest } from '../../lib/admin-auth';
import PrintButton from './print-button';
export const dynamic = 'force-dynamic';

const courses=[['Modulação e B.O. PM','BASE','4h','Comunicação, registro padronizado e fluxo de informação.'],['P.O.P. / Carceragem','BASE','4h','Procedimentos, responsabilidades e documentação.'],['Abordagem e Posicionamento','BASE','6h','Postura, comunicação e segurança no atendimento.'],['Direção Defensiva','MOBILIDADE','6h','Condução responsável, prevenção e decisão.'],['TAT I','TÁTICO','8h','Fundamentos, disciplina e progressão formativa.'],['TAT II','TÁTICO','8h','Integração e resolução de cenários simulados.'],['TAT III','TÁTICO','10h','Liderança, coordenação e avaliação avançada.'],['SAT-A','ESPECIALIZAÇÃO','6h','Aperfeiçoamento técnico supervisionado.'],['SAT-B','ESPECIALIZAÇÃO','8h','Consolidação e certificação de competência.'],['CFC','FORMAÇÃO','12h','Formação para liderança, instrução e gestão.'],['Pelotão RPM / ROCAM','MOTOCICLETAS','8h','Mobilidade, patrulhamento e coordenação.'],['Comandante RPM / ROCAM','COMANDO','10h','Planejamento, liderança e supervisão.']];
const roster=[['TEN-CEL','Rafael Aguiar','Responsável geral'],['MAJ PM','Jeraldo','Subcomando'],['CAP PM','Gabriel Santos','RH, desenvolvimento, tecnologia e criação do projeto'],['1º TEN PM','Valdir','Oficial'],['2º TEN PM','H. Smith','Unidade de motos'],['ASP PM','Vitor','Oficial em formação'],['1º SGT PM','Derek Oliveira','Graduação'],['1º SGT PM','Vitor Hugo','Graduação'],['3º SGT PM','Jota Bueno','Graduação'],['ALN SGT PM','Arthur Portella','Formação'],['CB PM','Marcos Silva','Efetivo'],['CB PM','Felipe Almeida','Efetivo'],['CB PM','Maycon Rios','Efetivo'],['SD PM','Joao Cavalcante','Efetivo'],['SD PM','Matheus Silva','Efetivo'],['SD PM','Birel Costa','Efetivo']];
const programs=[['FORMAÇÃO CONTÍNUA','Trilhas, avaliações, reciclagens e registro do desenvolvimento.'],['PRONTIDÃO','Disponibilidade, funções, escalas e meios acompanhados.'],['MOBILIDADE','Preparação da unidade de motocicletas e integração.'],['LIDERANÇA','Desenvolvimento de graduados e oficiais.'],['PADRONIZAÇÃO','Briefing, comunicação, relatórios e critérios comuns.'],['MELHORIA CONTÍNUA','Debriefing, indicadores e plano de correção.']];
const operations=[['01','LEITURA DO CENÁRIO','Setores, horários, demandas e prioridades.'],['02','PLANEJAMENTO','Objetivo, responsáveis, recursos e critérios.'],['03','DISTRIBUIÇÃO','Equipes, funções, liderança e substituições.'],['04','EXECUÇÃO','Briefing, supervisão, comunicação e registro.'],['05','AVALIAÇÃO','Debriefing, resultados, lições e melhorias.']];
const gallery=[['01-apresentacao-da-equipe.jpg','Apresentação e prontidão'],['02-briefing-operacional.jpg','Briefing operacional'],['03-formatura-e-disciplina.jpg','Formatura e disciplina'],['04-prontidao-da-unidade.jpg','Prontidão da unidade'],['05-presenca-comunitaria.jpg','Presença comunitária virtual'],['06-integracao-e-prontidao.jpg','Integração operacional']];
function H({n,e,t}:{n:string;e:string;t:string}){return <header><span>{n}</span><div><small>{e}</small><h2>{t}</h2></div></header>}
export default async function DocumentPage(){if(!await isAdminRequest())redirect('/admin');return <main className="project-document"><nav className="document-tools"><a href="/admin">← VOLTAR AO PAINEL</a><span>Projeto completo · escolha “Salvar como PDF”.</span><PrintButton/></nav>
<section className="doc-cover"><div className="doc-mark">18</div><small>18º BPM/M — VIRTUAL</small><h1>PROJETO COMPLETO DE<br/><em>IMPLANTAÇÃO BAEP</em></h1><p>Identidade, programas, atuação, estrutura, formação, gestão, implantação e memória visual.</p><footer><b>DOCUMENTO INTEGRAL</b><span>VERSÃO {new Date().getFullYear()}</span></footer></section>
<section className="doc-page"><H n="01" e="VISÃO EXECUTIVA" t="IDENTIDADE E PROPÓSITO"/><p className="doc-lead">Construir uma unidade virtual organizada, preparada e adaptável à cidade que receber o projeto, com comando definido, formação progressiva e acompanhamento contínuo.</p><div className="doc-columns">{[['MISSÃO','Excelência apoiada em disciplina, preparo, presença e liderança.'],['VISÃO','Referência virtual em organização, formação e evolução.'],['ENTREGA','Proposta geral, sem território fixo, pronta para adaptação.']].map(x=><article key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><h3 className="doc-subtitle">PILARES</h3><ul className="doc-list"><li>Comando e responsabilidades definidos.</li><li>Formação teórica, prática e reciclagem.</li><li>Comunicação e registros padronizados.</li><li>Indicadores, revisão e melhoria contínua.</li></ul><aside className="doc-note"><b>ESCOPO</b><p>Projeto virtual independente para apresentação e simulação, sem vínculo com órgãos públicos reais.</p></aside></section>
<section className="doc-page"><H n="02" e="PORTFÓLIO ESTRATÉGICO" t="PROGRAMAS DA UNIDADE"/><div className="doc-programs">{programs.map((x,i)=><article key={x[0]}><b>{String(i+1).padStart(2,'0')}</b><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><h3 className="doc-subtitle">COMPROMISSOS</h3><ul className="doc-list"><li>Calendário e critérios divulgados previamente.</li><li>Responsável e resultado definidos por programa.</li><li>Revisão periódica pelo comando.</li><li>Proteção das informações internas.</li></ul></section>
<section className="doc-page"><H n="03" e="MODELO DE ATUAÇÃO" t="COMO VAMOS TRABALHAR"/><div className="doc-operations">{operations.map(x=><article key={x[0]}><b>{x[0]}</b><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div><div className="doc-columns">{[['ANTES','Diagnóstico, equipes, recursos e briefing.'],['DURANTE','Supervisão, comunicação e atualização.'],['DEPOIS','Relatório, feedback e melhoria.']].map(x=><article key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><aside className="doc-note"><b>ADAPTAÇÃO</b><p>Setores, horários e prioridades serão definidos conforme a realidade da cidade de implantação.</p></aside></section>
<section className="doc-page"><H n="04" e="CADEIA DE COMANDO" t="HIERARQUIA COMPLETA"/><div className="doc-roster">{roster.map((x,i)=><article key={x[1]}><b>{String(i+1).padStart(2,'0')}</b><strong>{x[0]}</strong><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div><aside className="doc-note"><b>TECNOLOGIA E RH</b><p>O CAP PM Gabriel Santos é o criador do projeto e responsável pelos desenvolvimentos e iniciativas tecnológicas, além da gestão de RH.</p></aside></section>
<section className="doc-page"><H n="05" e="ACADEMIA DE FORMAÇÃO" t="OS 12 CURSOS PROPOSTOS"/><div className="doc-course-table detailed"><div><b>CURSO / NÍVEL</b><b>CARGA</b><b>CONTEÚDO</b></div>{courses.map(x=><div key={x[0]}><strong>{x[0]}<small>{x[1]}</small></strong><span>{x[2]}</span><p>{x[3]}<em>Avaliação teórica e prática.</em></p></div>)}</div></section>
<section className="doc-page"><H n="06" e="SISTEMA FORMATIVO" t="APLICAÇÃO E RESULTADOS"/><div className="doc-phases training">{[['01','INSCRIÇÃO','Pré-requisitos'],['02','INSTRUÇÃO','Teoria orientada'],['03','SIMULAÇÃO','Prática supervisionada'],['04','AVALIAÇÃO','Critérios objetivos'],['05','CERTIFICAÇÃO','Registro e validade'],['06','ACOMPANHAMENTO','Feedback e reciclagem']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><h3 className="doc-subtitle">RESULTADOS</h3><ul className="doc-list"><li>Padronização de procedimentos e linguagem.</li><li>Prontidão e segurança nas funções.</li><li>Lideranças capazes de desenvolver equipes.</li><li>Falhas convertidas em novos treinamentos.</li></ul></section>
<section className="doc-page"><H n="07" e="GOVERNANÇA" t="GESTÃO E INDICADORES"/><div className="doc-programs management">{[['COMANDO GERAL','Direção e validação.'],['SUBCOMANDO','Coordenação e supervisão.'],['RH E TECNOLOGIA','Pessoas, sistemas e projeto.'],['UNIDADE DE MOTOS','Formação e mobilidade.'],['INSTRUÇÃO','Calendário e certificações.'],['QUALIDADE','Relatórios e melhorias.']].map((x,i)=><article key={x[0]}><b>0{i+1}</b><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><div className="doc-indicators">{['EFETIVO','FORMAÇÃO','DISCIPLINA','OPERAÇÃO','LIDERANÇA','QUALIDADE'].map(x=><div key={x}><b>{x}</b><span>Acompanhamento periódico</span></div>)}</div></section>
<section className="doc-page"><H n="08" e="ROTEIRO DE ENTREGA" t="IMPLANTAÇÃO E PRONTIDÃO"/><div className="doc-phases">{[['01','ESTRUTURAÇÃO','Comando, funções e documentos.'],['02','CAPACITAÇÃO','Cursos e exercícios.'],['03','VALIDAÇÃO','Avaliações e prontidão.'],['04','ATIVAÇÃO','Início e melhoria contínua.']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><h3 className="doc-subtitle">PORTÃO DE ATIVAÇÃO</h3><ul className="doc-list"><li>Comando, efetivo e escalas validados.</li><li>Formações obrigatórias concluídas.</li><li>Rotinas e comunicação testadas.</li><li>Recursos e responsáveis definidos.</li><li>Plano de 90 dias e revisão aprovados.</li></ul></section>
<section className="doc-page"><H n="09" e="MEMÓRIA VISUAL" t="GALERIA DE ATUAÇÃO VIRTUAL"/><div className="doc-gallery">{gallery.map((x,i)=><figure key={x[0]}><img src={`/gallery/${x[0]}`} alt={x[1]}/><figcaption><b>0{i+1}</b>{x[1]}</figcaption></figure>)}</div><p className="doc-footnote">Seleção do acervo. A galeria completa permanece disponível no site.</p></section>
<section className="doc-page doc-closing"><H n="10" e="ENCERRAMENTO" t="PRONTOS PARA EVOLUIR"/><p className="doc-lead">Uma unidade virtual forte nasce da combinação entre pessoas preparadas, liderança responsável, processos claros e capacidade permanente de aprender.</p><div className="doc-columns">{[['DISCIPLINA','Postura e responsabilidade.'],['PREPARO','Formação progressiva.'],['PRESENÇA','Integração e compromisso.']].map(x=><article key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><footer className="doc-sign"><div><span>COMANDO GERAL</span></div><div><span>RESPONSÁVEL PELO PROJETO</span></div></footer><div className="doc-final-mark">18º BPM/M<br/><small>PROJETO BAEP · VIRTUAL</small></div></section>
<footer className="doc-disclaimer">PROJETO VIRTUAL INDEPENDENTE · SEM VÍNCULO COM ÓRGÃOS PÚBLICOS REAIS</footer></main>}
